// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "test.h"

int main(int argc, char **argv) {
    Fl_Double_Window* w = new Fl_Double_Window(500, 100);
    w->color((Fl_Color)43);

    new Fl_Button(100, 50, 50, 30, "button");

    w->end();
    w->show(argc, argv);
    return Fl::run();
}
