// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include <iostream>

#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>

#include "variable.h"



using namespace std;


// global var
//

Fl_Window* w;

Fl_Group* lcm_group;
Fl_Group* gcd_group;
Fl_Group* sincos_group;
Fl_Group* heron_group;
Fl_Group* se_group;
Fl_Group* twopow_group;


Fl_Input* gcd_number_input;


void hide_all(void) {

    lcm_group->hide();
    gcd_group->hide();
    sincos_group->hide();
    heron_group->hide();
    se_group->hide();
    twopow_group->hide();
}


void gcd_cb(Fl_Widget* w, void*) {
    hide_all();
    gcd_group->show(); 
}


void lcm_cb(Fl_Widget* w, void*) {
    hide_all();
    lcm_group->show(); 
}


void sincos_cb( Fl_Widget* w, void* ) {
    hide_all();
    sincos_group->show();
    //cout << "sin cos" << endl;
}
void heron_cb( Fl_Widget* w, void* ) {
    hide_all();
    heron_group->show();
}

void se_cb( Fl_Widget* w, void*) {
    hide_all();
    se_group->show();
}

void twopow_cb( Fl_Widget* w, void*) {
    hide_all();
    twopow_group->show();
}





void make_ui(void) {
    w = new Fl_Window(800, 500);
    w->color((Fl_Color)45);
    Fl_Menu_Bar* bar = new Fl_Menu_Bar(160, 0, 1365, 25);
	    
    bar->add("gcd", 0, gcd_cb);
    bar->add("lcm", 0, lcm_cb);



    Fl_Menu_Button* menu_triangle = new Fl_Menu_Button(0, 0, 80, 25, "triangle");

    menu_triangle->add("sin,cos", 0, sincos_cb);
    menu_triangle->add("heron\'s", 0, heron_cb);


    Fl_Menu_Button* menu_alg = new Fl_Menu_Button(80, 0, 80, 25, "algebra");
    menu_alg->add("se", 0, se_cb);
    menu_alg->add("2powEq", 0, twopow_cb);


    



    gcd_group = new Fl_Group(100, 70, 600, 500);
    

    
    gcd_number_input = new Fl_Input(300, 100, 270, 30, "numbers");

    Fl_Button* gcd_calc_btn = new Fl_Button(350, 200, 50, 30, "calc");

    gcd_calc_btn->callback(gcd_calc, 0);


    Fl_Box* gcd_output_text = new Fl_Box(350, 300, 50, 30, "gcd: ");


    gcd_group->end();

    gcd_group->hide();





    
    lcm_group = new Fl_Group(100, 70, 600, 500);
    

    lcm_group->end();

    lcm_group->hide();





    sincos_group = new Fl_Group(100, 70, 600, 500);

    sincos_group->end();
    sincos_group->hide();





    heron_group = new Fl_Group(100, 70, 600, 500);
    
    heron_group->end();
    heron_group->hide();





    se_group = new Fl_Group(100, 70, 600, 500);
    

    se_group->end();
    se_group->hide();




    
    twopow_group = new Fl_Group(100, 70, 600, 500);
    

    twopow_group->end();
    twopow_group->hide();





    w->end();
    
}
