// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include <iostream>

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Menu_Button.H>


using namespace std;



Fl_Menu_Item menu_algebra[] = {
 {"se", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2powEq", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};



void gcd_cb(Fl_Widget* w, void*) {
    Fl_Menu_Bar *bar = (Fl_Menu_Bar*) w;
    const Fl_Menu_Item * item =  bar->mvalue();
    cout <<  item->label() << "\n";
}

void sincos( Fl_Widget* w, void* ) {
    cout << "sin cos" << endl;
}
void heron( Fl_Widget* w, void* ) {
    cout << "heron" << endl;
}


int main(int argc, char **argv) {
    Fl_Double_Window* w = new Fl_Double_Window(600, 400);
    w->color((Fl_Color)55);
    Fl_Menu_Bar* bar = new Fl_Menu_Bar(160, 0, 1365, 25);
	    
    bar->add("gcd", 0, gcd_cb);
    bar->add("lcm", 0, gcd_cb);



    Fl_Menu_Button* menu_triangle = new Fl_Menu_Button(0, 0, 80, 25, "triangle");
    //triangle->menu(menu_triangle);
    menu_triangle->add("sin,cos", 0, sincos);
    menu_triangle->add("heron\'s", 0, heron);

    Fl_Menu_Button* alg = new Fl_Menu_Button(80, 0, 80, 25, "algebra");
    alg->menu(menu_algebra);

    
    w->end();
    w->show(argc, argv);
    return Fl::run();
}
